on:
  push:
    paths:
      - images/dash/**
  workflow_dispatch:

env:
  image_name: dash
  registry: gitea.epichouse.co.uk
  owner: dan
  dev_server: ldnapptst1
  dev_compose_project: dash-test
  prod_server: ldnappprd1
  prod_compose_project: dash
  deploy_image: true

jobs:
  build-dev:
    runs-on: london
    defaults:
      run:
        working-directory: ./images/${{ env.image_name }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Authenticate with Gitea
        run: docker login ${{ env.registry }} -u ${{ secrets.username }} -p ${{ secrets.password }}
      - name: Build Docker Image
        run: docker build -t ${{ env.registry }}/${{ env.owner }}/${{ env.image_name }}:latest -f dockerfile .
      - name: Push Docker Image
        run: docker push ${{ env.registry }}/${{ env.owner }}/${{ env.image_name }}:latest
  deploy-dev:
    runs-on: london
    if: ${{ env.deploy_image == 'true' }}
    needs: build-dev
    steps:
      - name: Pull latest image on ${{ env.dev_server }}
        run: |
          ssh sa@${{ env.dev_server }} \
          "sudo docker compose -f /var/lib/docker/compose/${{ env.dev_compose_project }}/compose.yml pull \
          && sudo docker compose -f /var/lib/docker/compose/${{ env.dev_compose_project }}/compose.yml up -d"

  build-prod:
    runs-on: london
    defaults:
      run:
        working-directory: ./images/${{ env.image_name }}
    needs: deploy-dev
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Authenticate with Gitea
        run: docker login ${{ env.registry }} -u ${{ secrets.username }} -p ${{ secrets.password }}
      - name: Build Docker Image
        run: docker build -t ${{ env.registry }}/${{ env.owner }}/${{ env.image_name }}:latest -f dockerfile .
      - name: Push Docker Image
        run: docker push ${{ env.registry }}/${{ env.owner }}/${{ env.image_name }}:latest
  deploy-prod:
    runs-on: london
    if: ${{ env.deploy_image == 'true' }}
    needs: build-prod
    steps:
      - name: Pull latest image on ${{ env.prod_server }}
        run: |
          ssh sa@${{ env.prod_server }} \
          "sudo docker compose -f /var/lib/docker/compose/${{ env.prod_compose_project }}/compose.yml pull \
          && sudo docker compose -f /var/lib/docker/compose/${{ env.prod_compose_project }}/compose.yml up -d"