on:
  push:
    paths:
      - images/dash/**
  workflow_dispatch:
    inputs:
      dev_deploy:
        description: 'Deploy Dev'
        required: false
        type: boolean
        defaults: true
      prod_deploy:
        description: 'Deploy Dev'
        required: false
        type: boolean

env:
  image_location: ./images/dash
  image_name: dash
  registry: gitea.epichouse.co.uk
  owner: dan
  dev_server: ldnapptst1
  dev_compose_project: dash-test
  dev_deploy: "true"
  prod_server: ldnappprd1
  prod_compose_project: dash
  prod_deploy: "true"

jobs:
  build_dev:
    runs-on: london
    defaults:
      run:
        working-directory: ${{ env.image_location }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Authenticate with Gitea
        run: docker login ${{ env.registry }} -u ${{ secrets.username }} -p ${{ secrets.password }}
      - name: Build Docker Image
        run: docker build -t ${{ env.registry }}/${{ env.owner }}/${{ env.image_name }}:development -f dockerfile .
      - name: Push Docker Image
        run: docker push ${{ env.registry }}/${{ env.owner }}/${{ env.image_name }}:development
  deploy_dev:
    runs-on: london
    if: ${{ inputs.dev_deploy || true }}
    needs: build_dev
    steps:
      - name: Pull Image (DEV)
        run: |
          sshpass -p ${{ secrets.sa_password }} ssh sa@${{ env.dev_server }} -o StrictHostKeyChecking=accept-new \
          "sudo docker compose -f /var/lib/docker/compose/${{ env.dev_compose_project }}.yml pull \
          && sudo docker compose -f /var/lib/docker/compose/${{ env.dev_compose_project }}.yml up -d"

  build_prod:
    runs-on: london
    defaults:
      run:
        working-directory: ${{ env.image_location }}
    needs: deploy_dev
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Authenticate with Gitea
        run: docker login ${{ env.registry }} -u ${{ secrets.username }} -p ${{ secrets.password }}
      - name: Build Docker Image
        run: docker build -t ${{ env.registry }}/${{ env.owner }}/${{ env.image_name }}:latest -f dockerfile .
      - name: Push Docker Image
        run: docker push ${{ env.registry }}/${{ env.owner }}/${{ env.image_name }}:latest
  deploy_prod:
    runs-on: london
    if: ${{ inputs.prod_deploy || false }}
    needs: build_prod
    steps:
      - name: Pull Image (PROD)
        run: |
          ssh sa@${{ env.prod_server }} \
          "sudo docker compose -f /var/lib/docker/compose/${{ env.prod_compose_project }}.yml pull \
          && sudo docker compose -f /var/lib/docker/compose/${{ env.prod_compose_project }}.yml up -d"