site_name: Homelab Documentation
docs_dir: /docs/documentation
repo_url: https://gitea.epichouse.co.uk/dan/homelab-mgmt
repo_name: homelab-mgmt

theme:
  name: material
  logo: ../images/homelab.png
  favicon: ../images/homelab.png
  palette:
    - scheme: slate
      primary: black
extra:
  generator: false