name: Docker - Dashy Build & Deploy
on:
  workflow_dispatch:
    inputs:
      build_dev:
        description: 'Build Development Image'
        required: false
        default: true
        type: boolean
      build_prod:
        description: 'Build Production Image'
        required: false
        default: false
        type: boolean

jobs:
  development:
    permissions:
      contents: read
      packages: write
    if: ${{ github.event.inputs.build_dev == true}}
    uses: epichouse/workflow-templates/.github/workflows/docker-build.yaml@main
    with:
      docker_env: development
      docker_project: "images/dashy"

  production:
    needs: development
    permissions:
      contents: read
      packages: write
    if: ${{ github.event.inputs.build_prod == true}}
    uses: epichouse/workflow-templates/.github/workflows/docker-build.yaml@main
    with:
      docker_env: latest
      docker_project: "images/dashy"
