name: Build Dashy Project

on:
  workflow_dispatch:
    inputs:
      build_dev:
        description: 'Build Development Image'
        required: true
        default: true
        type: boolean
      build_prod:
        description: 'Build Production Image'
        required: true
        default: false
        type: boolean

jobs:
  development:
    permissions:
      contents: read
      packages: write
    if: ${{ github.event.inputs.build_dev == 'true' }}
    uses: epichouse/workflow-templates/.github/workflows/docker-build.yaml@main
    with:
      image_tag: development
      image_name: dashy
      build_path: images/dashy

  production:
    needs: development
    permissions:
      contents: read
      packages: write
    if: ${{ github.event.inputs.build_prod == 'true' }}
    uses: epichouse/workflow-templates/.github/workflows/docker-build.yaml@main
    with:
      image_tag: latest
      image_name: dashy
      build_path: images/dashy