name: dash
on:
  workflow_dispatch:
  push:
    paths:
      - 'images/dash/**'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  dev_build:
    uses: epichouse/github-templates/.github/workflows/docker_build.yaml@main
    with:
      image_tag: development
      image_name: dash
      build_path: images/dash
  dev_deploy:
    uses: epichouse/github-templates/.github/workflows/docker_pull.yaml@main
    needs: dev_build
    with:
      docker_server: ldnapptst1
      docker_compose_project: dash-test