name: link-page
on:
  workflow_dispatch:
  push:
    paths:
      - 'images/link-page/**'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  dev_build:
    uses: epichouse/github-templates/.github/workflows/docker_build.yaml@main
    with:
      image_tag: development
      image_name: link-page
      build_path: images/link-page
  # dev_deploy:
  #   uses: epichouse/github-templates/.github/workflows/docker_pull.yaml@main
  #   needs: dev_build
  #   with:
  #     docker_server: ldnapptst1
  #     docker_compose_project: link-page-test
  prod_build:
    uses: epichouse/github-templates/.github/workflows/docker_build.yaml@main
    needs: dev_build
    with:
      image_tag: latest
      image_name: link-page
      build_path: images/link-page
  # prod_deploy:
  #   uses: epichouse/github-templates/.github/workflows/docker_pull.yaml@main
  #   needs: prod_build
  #   with:
  #     docker_server: ldnappprd1
  #     docker_compose_project: link-page